name: Android build

on: [workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        arch: [ "arm64" ]
      fail-fast: false

    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Build for Android ${{matrix.arch}}
      run: |
        export BUILD_ARCH=${{matrix.arch}}
        bash ci_build_android.bash

    - name: Upload
      uses: actions/upload-artifact@main
      with:
        name: file
        path: |
              lib/
              include/
        
